---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: latest

inputs:
- name: my-pipeline

run:
  path: my-pipeline/4-pipeline-for-bosh-create-env/pipelines/tasks/director-pinger/task

params:
  DIRECTOR_IP: ~
