#!/bin/bash

true ${PIPELINE_DIR:?"!"}
true ${BOSH_DEPLOYMENT_DIR:?"!"}
true ${STATE_DIR:?"!"}

bosh create-env $BOSH_DEPLOYMENT_DIR/bosh.yml \
  --state=$STATE_DIR/director/state.json \
  --vars-file=$STATE_DIR/director/vars.yml \
  --vars-store=$STATE_DIR/director/creds.yml \
  -o $BOSH_DEPLOYMENT_DIR/aws/cpi.yml \
  -o $BOSH_DEPLOYMENT_DIR/external-ip-with-registry-not-recommended.yml \
  -o $PIPELINE_DIR/operations/versions.yml \
;
