---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
- name: deployment-state
- name: my-pipeline
- name: cf-deployment

outputs:
- name: updated-deployment-state

run:
  path: my-pipeline/4-pipeline-for-bosh-create-env/pipelines/tasks/deploy-cf/task

params:
  PIPELINE_DIR: ~
  STEMCELL_URL: ~
  IN_STATE_DIR: deployment-state
  OUT_STATE_DIR: updated-deployment-state
