#!/bin/bash

true ${PIPELINE_DIR:?"!"}
true ${STEMCELL_URL:?"!"}
true ${IN_STATE_DIR:?"!"}
true ${OUT_STATE_DIR:?"!"}

source $IN_STATE_DIR/director/bosh-env.sh
true ${BOSH_CLIENT:?"!"}
true ${BOSH_CLIENT_SECRET:?"!"}
true ${BOSH_ENVIRONMENT:?"!"}
true ${BOSH_CA_CERT:?"!"}

bosh alias-env bosh-env

bosh upload-stemcell \
  --environment bosh-env \
  $STEMCELL_URL \
;

bosh deploy \
  cf-deployment/cf-deployment.yml \
  --environment bosh-env \
  --deployment cf \
  --vars-file=$IN_STATE_DIR/cf/vars.yml \
  --vars-store=$IN_STATE_DIR/cf/creds.yml \
  -o cf-deployment/operations/aws.yml \
  -o cf-deployment/operations/change-logging-port-for-aws-elb.yml \
  -o cf-deployment/operations/scale-to-one-az.yml \
  --non-interactive \
;

trap "cp -r $IN_STATE_DIR/ $OUT_STATE_DIR/; cd $OUT_STATE_DIR; git add -A; git ci -m'Updated state' --author 'CI <ci@young.io>'" EXIT
