---
name: concourse
releases:
- name: concourse
  url: https://bosh.io/d/github.com/concourse/concourse?v=3.5.0
  sha1: 65a974b3831bb9908661a5ffffbe456e10185149
  version: 3.5.0
- name: garden-runc
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.9.3
  sha1: a153fd2b9d85d01772e9c6907b8c9e5005059c9e
  version: 1.9.3
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest
instance_groups:
- name: web
  instances: 1
  vm_type: ((concourse_vm_type))
  vm_extensions: [((concourse_web_vm_extensions))]
  stemcell: trusty
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: atc
    release: concourse
    properties:
      external_url: ((concourse_external_url))
      basic_auth_username: ((concourse_basic_auth_username))
      basic_auth_password: ((concourse_basic_auth_password))
      postgresql_database: ((concourse_atc_db_name))
  - name: tsa
    release: concourse
    properties: {}
- name: db
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: ((concourse_vm_type))
  stemcell: trusty
  # replace with a disk type from your BOSH Director's cloud config
  persistent_disk_type: ((concourse_db_disk_type))
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: ((concourse_atc_db_name))
        role: ((concourse_atc_db_role))
        password: ((concourse_atc_db_password))
- name: worker
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: ((concourse_vm_type))
  vm_extensions: [((concourse_worker_vm_extensions))]
  stemcell: trusty
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
