bbl_env_name:
bbl_aws_region:
bbl_aws_access_key_id:
bbl_aws_secret_access_key:
bbl_lbs_ssl_cert:
bbl_lbs_ssl_signing_key:
pipeline_repo_url:
tasks_dir:
state_repo_url:
state_repo_private_key:
system_domain:
