groups:
- name: create-env-deployment
  jobs:
  - create-infrastructure
  - deploy-director
#  - configure-cf
#  - upgrade-cf
resources:
#- name: vars-store
#  type: git
#  source:
#    branch: master
#    uri: {{state_repo_url}}
#    private_key: {{state_repo_private_key}}
#    paths:
#    - deployment-vars.yml
- name: deployment-state
  type: git
  source:
    branch: master
    uri: {{state_repo_url}}
    private_key: {{state_repo_private_key}}
- name: pipeline-tasks
  type: git
  source:
    branch: master
    uri: {{pipeline_repo_url}}
#- name: cf-deployment
#  type: git
#  source:
#    branch: master
#    uri: https://github.com/cloudfoundry/cf-deployment.git
- name: bosh-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-deployment.git
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
jobs:
- name: create-infrastructure
  serial: true
  build_logs_to_retain: 10
  plan:
  - aggregate:
    - get: deployment-state
    - get: pipeline-tasks
    - get: cf-deployment-concourse-tasks
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: aws
      BBL_AWS_REGION: {{bbl_aws_region}}
      BBL_AWS_ACCESS_KEY_ID: {{bbl_aws_access_key_id}}
      BBL_AWS_SECRET_ACCESS_KEY: {{bbl_aws_secret_access_key}}
      BBL_LB_CERT: {{bbl_lbs_ssl_cert}}
      BBL_LB_KEY: {{bbl_lbs_ssl_signing_key}}
      BBL_ENV_NAME: {{bbl_env_name}}
    ensure:
      put: deployment-state
      params:
        repository: updated-deployment-state
        rebase: true
- name: deploy-director
  serial: true
  build_logs_to_retain: 10
  plan:
  - aggregate:
    - get: deployment-state
      passed: [create-infrastructure]
    - get: pipeline-tasks
      passed: [create-infrastructure]
    - get: bosh-deployment
  - task: generate-manifests
    file: pipeline-dir/4-pipeline-for-bosh-create-env/tasks/deploy-director/task.yml
    input_mapping:
      pipeline-tasks: pipeline-dir/4-pipeline-for-bosh-create-env/tasks
    ensure:
      put: deployment-state
      params:
        repository: updated-deployment-state
        rebase: true
  # bosh delete-env using bbl state
