---
groups:
- name: cf-deployment
  jobs:
  - update-bosh
  - update-cf
resources:
- name: vars-store
  type: git
  source:
    branch: master
    uri: {{state_repo_url}}
    private_key: {{state_repo_private_key}}
    paths:
    - deployment-vars.yml
- name: bbl-state
  type: git
  source:
    branch: master
    uri: {{state_repo_url}}
    private_key: {{state_repo_private_key}}
    paths:
    - bbl-state.json
- name: cf-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
jobs:
- name: update-bosh
  serial_groups: [bosh-cf]
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: bbl-state
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: aws
      BBL_AWS_REGION: {{bbl_aws_region}}
      BBL_AWS_ACCESS_KEY_ID: {{bbl_aws_access_key_id}}
      BBL_AWS_SECRET_ACCESS_KEY: {{bbl_aws_secret_access_key}}
      BBL_LB_CERT: {{bbl_lbs_ssl_cert}}
      BBL_LB_KEY: {{bbl_lbs_ssl_signing_key}}
      BBL_ENV_NAME: {{bbl_env_name}}
    input_mapping:
      bbl-state: bbl-state
    ensure:
      put: bbl-state
      params:
        repository: updated-bbl-state
        rebase: true
- name: update-cf
  serial_groups: [bosh-cf]
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: cf-deployment
    - get: bbl-state
    - get: vars-store
  - task: bosh-deploy-cf
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      bbl-state: bbl-state
      cf-deployment: cf-deployment
      ops-files: cf-deployment
      vars-store: vars-store
    params:
      SYSTEM_DOMAIN: {{system_domain}}
      OPS_FILES: "operations/aws.yml operations/change-logging-port-for-aws-elb.yml operations/disable-router-tls-termination.yml operations/scale-to-one-az.yml"
    ensure:
      put: vars-store
      params:
        repository: updated-vars-store
        rebase: true
